CREATE DATABASE IF NOT EXISTS todo_list CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE todo_list;

CREATE TABLE IF NOT EXISTS todo (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL COMMENT '标题',
  description TEXT COMMENT '描述',
  completed BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否完成',
  category VARCHAR(50) DEFAULT 'personal' COMMENT '分类',
  priority INT NOT NULL DEFAULT 1 COMMENT '优先级(1-低, 2-中, 3-高)',
  due_date DATETIME COMMENT '截止日期',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;