USE todo_list;

CREATE TABLE IF NOT EXISTS user (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
  password VARCHAR(255) NOT NULL COMMENT '加密后的密码',
  email VARCHAR(100) UNIQUE COMMENT '邮箱',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

ALTER TABLE todo ADD COLUMN user_id BIGINT NOT NULL DEFAULT 1 COMMENT '所属用户ID' AFTER id;


ALTER TABLE todo ADD CONSTRAINT fk_todo_user 
FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE;


CREATE INDEX idx_todo_user_id ON todo(user_id);

-- 密码是 'password123' 的 BCrypt 加密结果
INSERT INTO user (username, password) 
VALUES ('admin', '$2a$10$i0VSltvZ718294WxIDs80eEQPTn.SU.2bQnWJywncR1EJjfEZBxtK')
ON DUPLICATE KEY UPDATE password = VALUES(password);